[supervisord]
nodaemon=true

[program:instance]
command=/app/instance/bin/instance
directory=/app/instance
priority=10
autorestart=true

[program:auth]
command=/app/auth/bin/auth
directory=/app/auth
priority=20
autorestart=true

[program:gateway]
command=/app/gateway/bin/gateway
directory=/app/gateway
priority=20
autorestart=true

[program:service/account]
command=/app/account/bin/service/account
directory=/app/service/account
priority=20
autorestart=true

[program:service/profile]
command=/app/profile/bin/service/profile
directory=/app/service/profile
priority=20
autorestart=true

[program:storage]
command=/app/storage/bin/storage
directory=/app/storage
priority=20
autorestart=true

[program:web]
command=/root/.bun/bin/bun start
directory=/app/web
priority=30
autorestart=true