export default {
  light: {
    primary: "#3b82f6",
    secondary: "#ff8743",
    tertiary: "#c23daf",
    on_primary: "#000",
    on_secondary: "#fff",
    on_tertiary: "#fff",
    surface: "#fdfdfd",
    surface_1: "#fcfcfc",
    surface_2: "#fafafa",
    background: "#f2f2f2",
    on_surface: "#000",
    on_background: "#000",
  },
  dark: {
    primary: "#3b82f6",
    secondary: "#ff8743",
    tertiary: "#c23daf",
    on_primary: "#000",
    on_secondary: "#fff",
    on_tertiary: "#fff",
    surface: "#1b1b1b",
    surface_1: "#1c1c1e",
    surface_2: "#1f1f1f",
    background: "#18181B",
    on_surface: "#000",
    on_background: "#000",
  },
};
